adding optional delete reason, if not provided will default to 0, scr…
ONSdigital/blaise-totalmobile-services pull request #130
Opened 2022-08-31 22:19 UTC by Riceyo

…ipt now also ignores completed jobs

2022-09-05 08:32 UTC, tomphp requested changes

2022-09-05 08:32 UTC, tomphp commented on scripts/delete_totalmobile_jobs.py
> +            if job["visitComplete"] is not True:
You need to add `visitComplete` to https://github.com/ONSdigital/blaise-totalmobile-services/blob/c7fd34dbddb543c8ee293eff7f9a50610f475267/client/optimise.py#L12 to appease the type checker.

2022-09-05 08:32 UTC, tomphp commented on client/base.py
> +    def _delete(self, path: str, reason: str) -> requests.Response:
I believe that this is a generic delete method for all resources, not just _jobs_? If would probably make more sense to make this parameter into something like `json: Any = None` and pass in the structured object.

2022-09-07 07:26 UTC, JAWilliamsONS approved these changes

2022-09-07 08:43 UTC, tomphp commented on scripts/delete_totalmobile_jobs.py
> +            if job["visitComplete"] is not True:
Leaving this for now as mypy is happy.

2022-09-07 08:44 UTC, tomphp approved these changes

2022-09-07 08:44 UTC, merged